### ISSUE TITLE
Build: flexslider

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#222]
Either get Views flexslider working or use alpine.js

**Comment by cbrody** [comment]
@ncktrnr I haven't had a chance to look at this yet, sorry. Perhaps you could summarise the issue and ask @finnlewis to look at it?

**Comment by ncktrnr** [comment]
I’ve added a view to show publications within a slider on theme terms. Presently CSS only, but shows roughly what we need. There will be another slider/carousel type for the about page showing custom blocks. With this in mind it’s (probably)easier to implement and style via Alpine/Twig.

**Comment by finnlewis** [comment]
We'll deal with the views display on this issue. 

@ncktrnr will give me a view.

We can look at Flexslider for this or Alpine JS. 

Nick is easy - which ever easier. Alpine JS might be cleaner?

**Comment by ncktrnr** [comment]
An example publications slider can be seen on any theme term, for example https://pubs-dev.ac.iied.org/theme/climate-change
Content via a view called Publication slider. 
Presently CSS only with no previous/next controls 
Alpine example https://codepen.io/m-eckel/pen/oNxeVgp
Flexslider example http://flexslider.woothemes.com/carousel-min-max.html

**Comment by finnlewis** [comment]
Hey @ncktrnr (CC @cbrody ) !

Made some progress on this today, and have some questions.

I've built a module to provide a views style plugin that mimics the Alpine example.

It has a configuration form, and Swiper https://swiperjs.com/demos has about a billion options.

So I'm wondering how far we should go with config options.

Currently the slider looks a bit like this (need to relocate the arrows to be vertically aligned): 

![image](https://user-images.githubusercontent.com/326588/183146683-e5617dbd-b886-42ac-aee0-3cf00cc4cc62.png)

And it swipes and clicks left and right. 

The settings form currently looks like this: 

![image](https://user-images.githubusercontent.com/326588/183146885-07fc6988-7737-4b9a-92fe-ec33cd6b305c.png)

I was just  going through the parameters on the example at https://codepen.io/m-eckel/pen/oNxeVgp and allowing config for each.

Q1: How far do you think we want to go with this / what are the highest value parameters? 
Q2: Are there other config options not Swiper specific that we might need? 
Q3: Just realised that this is not really IIED specific, so I might refactor the name of the module to be swiper_views or some such to be able to share with the wider Drupal community, any thoughts or suggestions on that? 

Getting there, but I know the details will be important.

No rush on this, we can discuss next week, but if you do have immediate thoughts I might be able to do some more before we talk.

Either way, look forward to catching up next week.

Cheers!

Finn

**Comment by finnlewis** [comment]
Oh - the work is on this branch: https://github.com/IIED-org/IIED-main/tree/feature/222-slider

**Comment by ncktrnr** [comment]
This is looking great, 

Q1. I think for us the parameters can match tailwind, so 
sm	640px	@media (min-width: 640px) 
md	768px	@media (min-width: 768px) 
lg	1024px	@media (min-width: 1024px)
xl	1280px	@media (min-width: 1280px)
2xl	1536px	@media (min-width: 1536px)

The slider cards are fixed width, so don't need any more than 6 at widest. 

Q2. config options not Swiper... I can't think of anything specific. There's indeed about a billion options in the demo. Notes below on what options might be useful.

Q3. I agree, this may indeed be useful to others, swiper_views sounds good. 

General 
Prev/next buttons on both edges seems pretty common, otherwise positioning buttons above  is OK, but below only really works for mobile.

 Prev/next can jump either one at a time, or by by the entire visible list (like netflix). I prefer one at a time, but this could be a config option?

I don't think there's any need for progress bar or dots etc. However numbering slides might be useful (1/6, 2/6 etc.) 

Does need to support swiping gestures on mobile. Keyboard and mouse a bonus.

Probably single effect (slide) is fine, no fade option. Also don't really need options for animation timing or easing. 

Probably should loop by default. 

Generally worth keeping the Tailwind CSS with Scroll Snap as a fallback? 

Hope that's enough for now.

**Comment by finnlewis** [comment]
Thanks @ncktrnr - will crack on with all that in mind.

I'm not convinced about numbering slides for now, but we could add that in with a little design consideration if you really think it is needed.

Also discussed keeping the Tailwind CSS with Scroll Snap as a fallback, assuming this means a fallback for browsers without JavaScript. This would be a big one, so I'll not prioritise this for now, as it is a wider question that needs a site-wide policy. So many things will currently not work without JavaScript on the site, that we would need to check in on each of them.

**Comment by finnlewis** [comment]
Hi @ncktrnr  and @cbrody 

I've added the breakpoints, still a bit baffled by the vertical alignment of the arrows - something to do with relative / absolute positioning of things with tailwind I guess, maybe @ncktrnr you can help to resolve that. 

I also found this https://www.drupal.org/project/swiper_formatter which looks like it is pretty advanced. Not sure if you tried this @ncktrnr - I tested it and it did not immediately play ball, there were some odd styling issues, so I figure we stick with our custom module for now and make it play how we want. So there's not much worth sharing back with the Drupal community at this stage I think.

Here's a pull request to review the code and functionality: https://github.com/IIED-org/IIED-main/pull/369/files

**Comment by ncktrnr** [comment]
@finnlewis thanks again! 
Re: numbering slides, I agree we don't need that for now. Also agree on the fallback comment. I wasn't sure how that would work in practice anyway.

**Comment by cbrody** [comment]
@finnlewis thanks for this - I've merged into main, as this is now the default branch. Please make PRs against main going forward - cheers!

**Comment by cbrody** [comment]
I'm happy with this - OK to close @ncktrnr ?
