### ISSUE TITLE
Build: Views pages

### ISSUE THREAD

**Issue by cbrody** [IIED-org/IIED-main#227]
As necessary, these will be blocks embedded on terms
- [x] people

**Comment by cbrody** [comment]
@ncktrnr can you supply some test criteria?

**Comment by mattjobob** [comment]
Not sure what I'm testing? @ncktrnr - is this one for you to confirm?

**Comment by ncktrnr** [comment]
This is mainly just the people pages. We can mark this done if the correct people are showing. I think they are, but worth a quick check.

**Comment by mattjobob** [comment]
I don't think these are quite right, Eg on the climate change group page https://iied-main-stage.ac.iied.org/climate-change-research-group neither https://iied-main-stage.ac.iied.org/people/sejal-patel nor https://iied-main-stage.ac.iied.org/people/ebony-holland appear despite having CC checked on their group.

Is this view using the 'department' dropdown rather than the 'research group' checkboxes?

**Comment by ncktrnr** [comment]
You were right! Now updated to show the correct staff.
