### ISSUE TITLE
Fix: media centre pagination missing content

### ISSUE THREAD

**Issue by mattjobob** [IIED-org/IIED-main#574]
On the [media centre page](https://www.iied.org/media-centre), the paginated press releasses is not working properly. If you click on page 2, there is gap form the last date on page 1 (5 Dec) to the first on page 2 (6 Oct) - so there is missing content.

If you then click on page 1 again the content reappears, albeit in a much longer grid of content.

This might be related/similar to #475

**Comment by ncktrnr** [comment]
Issue is caused by differences in the view and layout builder settings. The view is set to paginate 24 items, layout builder was set to show only 8 items. I've removed the layout builder restrictions so the view now shows a paginated list of 24 with no content gaps. 

This seems like the best solution for users, but does mean the initial list is longer. The alternative would be to set the view to paginate 8 at a time and since that would mean a lot of clicks we could allow user to control the number of items displayed in the view.

**Comment by mattjobob** [comment]
Checked with Sarah and she's happy with 24. I think it's fine too
